version: "3.7"
services:
  rabbitmq:
    #image: rabbitmq:3.8-management-alpine
    image: rabbitmq:3.11-management
    container_name: 'rabbitmq'
    hostname: rabbit1
    ports:
        - 5672:5672
        - 15672:15672
    environment:
        RABBITMQ_DEFAULT_USER: guest
        RABBITMQ_DEFAULT_PASS: guest
    volumes:
        #único mapeamento que funcionou - banco de dados
        - ./docker-data/data:/var/lib/rabbitmq/mnesia
        #- ./docker-data/etc:/etc/rabbitmq
        #- ./docker-data/log:/var/log/rabbitmq
    #networks:
    #    - rabbitmq_srv_net

#networks:
#  rabbitmq_srv_net:
#    driver: bridge


#necessário configurar permissões específicas no volume do host
# sudo groupadd rabbitmq -g 999
# sudo useradd -u 999 -g 999 rabbitmq
# sudo chown -R rabbitmq:rabbitmq docker-data/

# docker run -it --rm --name rabbitmq -e hostname=rabbit1 -p 5672:5672 -p 15672:15672 -v  ~/rabbit-volume/log:/var/log/rabbitmq:rw -v ~/rabbit-volume/data/:/var/lib/rabbitmq/mnesia/:rw -v ~/rabbit-volume/etc/:/etc/rabbitmq/:rw rabbitmq:3.11-management